sudo: required

language: cpp

os:
    - linux

addons:
    apt:
        packages:
            - zlib
            - openssl
            - openssl-devel
            - gperf
            - php7-cli
            - php7-dev
            - php7-json
            - php7-embed

install:
    - cmake -DTDLIB_BUILD_TESTS=ON && make && sudo make install

script:
    - ./tester
    - php php_examples/func.php
