sudo: required

language: cpp

services:
    - docker

os:
    - linux

dist: xenial

matrix:
    include:
        - name: "Opensuse static build"
          env: os=opensuse linktype=static
        - name: "Opensuse shared build"
          env: os=opensuse linktype=shared

install:
    - $TRAVIS_BUILD_DIR/tests/scripts/build_docker.sh $os $linktype phptdlib/$os-$linktype

script:
    - docker run -it -v $TRAVIS_BUILD_DIR/php_examples:/php_examples phptdlib/$os-$linktype /php_examples/func.php
