sudo: required

language: cpp

os:
    - linux

dist: xenial

addons:
    apt:
        packages:
            - wget
            - openssl
            - libssl-dev
            - gperf
            - php-cli
            - php-dev
            - php-json
            - libphp-embed

before_install:
    - wget https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.tar.gz -O /opt/cmake.tar.gz
    - tar -czf /opt/cmake.tar.gz -C /opt

install:
    - /opt/cmake/cmake-3.13.2-Linux-x86_64/bin/cmake -DTDLIB_BUILD_TESTS=ON && make && sudo make install

script:
    - ./tester
    - php php_examples/func.php
